# Generated by Django 2.1.7 on 2019-02-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_raadnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raadnum',
            old_name='blog',
            new_name='post',
        ),
    ]
