# Generated by Django 2.1.7 on 2019-02-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190227_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaadNum',
            new_name='ReadNum',
        ),
    ]
