# Generated by Django 2.1.7 on 2019-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190227_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('qq', models.CharField(max_length=11)),
                ('group', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
